### ISSUE TITLE
macOS dpi wrong

### ISSUE THREAD

**Issue by MatthewBlanchard** [MFEK/glif#147]
There's a bug currently where mouse position is offset, but not in a uniform manner. The canvas and imgui seem to handle mouse position differently. This is confirmed on the newest Mac OS (only one I have access to). Needs further investigation.

**Comment by ctrlcctrlv** [comment]
Might be fixed by recent deprecation of calc_x/calc_y. @justvanrossum did not report any issue, so I'm closing this.

**Comment by ctrlcctrlv** [comment]
Reopening due to investigation by @subject38. I fixed half the problem.

**Comment by ctrlcctrlv** [comment]
Forgot that even _mentioning_ an issue ID in any commit closes.

Anyway, as I wrote in message of MFEK/imgui-skia-renderer.rlib@e6ba2e8—

 > #### Stop resetting matrix. Does this fix MFEK/glif#147, @Subject38?

**Comment by Subject38** [comment]
As far as I can tell after rebuilding and pulling the module manually to make sure it's using the right one, it does not fix the issue. Behavior remains the same both with mouse position and with rendering being offset incorrectly for the layers box

**Comment by ctrlcctrlv** [comment]
@Subject38 Try post-https://github.com/MFEK/glif/commit/7ada62d21133f72be9f1f981f36fc9e591ec4eee, which will make sure the right version is pulled.

**Comment by ctrlcctrlv** [comment]
Workaround available in https://github.com/MFEK/glif/commit/f5b761f8983dccd276d3a8a7db563d5d12c15c90. Unpinning until I can try myself on an M1 Macintosh.
